const express = require('express');
const router = express.Router();
const createUser = require('../controllers/LoginControllers/userRegister')
const loginuser = require('../controllers/LoginControllers/userLogin')
const loginadmin = require('../controllers/LoginControllers/adminLogin')
const createAdmin = require('../controllers/LoginControllers/adminRegister')
const createCourse = require('../controllers/CourseControllers/createCourse')
const updateTopic = require('../controllers/TopicControllers/updateTopic')
const del = require('../controllers/TopicControllers/delTopic')
const delcont = require('../controllers/ContentControllers/delCont')
const deleteCourse = require('../controllers/CourseControllers/delCourse')
const getCourse = require('../controllers/CourseControllers/getCourse')
const getTopic = require('../controllers/TopicControllers/getTopic')
const createTopic = require('../controllers/TopicControllers/createTopic')
const updateCourse = require('../controllers/CourseControllers/updateCourse')
const getContent = require('../controllers/ContentControllers/getCont')
const addContent = require('../controllers/ContentControllers/createCont')

router.post('/loginuser', loginuser)
router.delete('/delete/:cname', deleteCourse)
router.post('/registeruser', createUser)
router.post('/loginadmin', loginadmin)
router.post('/course', createCourse)
router.delete('/del/:tname', del)
router.delete('/delcont/:contname', delcont)
router.put('/course/:id', updateCourse)
router.patch('/topic3/:name', updateTopic)
router.post('/topic1/:coname', createTopic)
router.get('/topic/:cname', getTopic)
router.post('/content1/:toname', addContent)
router.get('/content/:tname', getContent)
router.get('/getcourse', getCourse)
module.exports = router;